# Generated by Django 4.2.3 on 2023-07-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkbase", "0003_base_server"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="password",
            field=models.CharField(max_length=50, verbose_name="Паролль"),
        ),
        migrations.AlterField(
            model_name="server",
            name="username",
            field=models.CharField(max_length=50, verbose_name="Пользователь"),
        ),
    ]
