# Generated by Django 4.2.3 on 2023-07-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkbase", "0004_alter_server_password_alter_server_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="password",
            field=models.CharField(max_length=50, verbose_name="Пароль"),
        ),
    ]
