# Generated by Django 4.2.3 on 2023-07-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkbase", "0005_alter_server_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="use_wa",
            field=models.BooleanField(default=False, verbose_name="win auth"),
        ),
    ]
